apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .values.image.repository }}:{{ .values.image.tag }}"
          imagePullPolicy: {{ .values.image.pullPolicy }}
          ports:
            - containerPort: {{ .values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .values.env.value }}
            resources:
              limits:
                cpu: {{ .values.resources.limits.cpu }}
                memory: {{ .values.resources.limits.memory }}
              requests:
                cpu: {{ .values.resources.requests.cpu }}
                memory: {{ .values.resources.requests.memory }}
            livenessProbe:
              httpGet:
                path: /health
                port: {{ .values.service.targetPort }}
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /health
                port: {{ .values.service.targetPort }}
              initialDelaySeconds: 5
              periodSeconds: 5